apiVersion: v1
kind: Service
metadata:
  labels:
    app: hero-feed-app
    branch: adidas-hero-develop
  name: hero-feed-service
spec:
  ports:
  - name: hero-feed-port
    nodePort: 30489
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: hero-feed-app
