apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    branch: adidas-hero-develop
  name: test-service
spec:
  ports:
  - name: test-port
    nodePort: 30489
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: test
