apiVersion: v1
kind: Namespace
metadata:
  name: stg-cn-northwest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: stg-cn-northwest
  namespace: stg-cn-northwest
spec:
  interval: 5m
  path: "./clusters/stg-cn-northwest/app1"
  prune: true
  targetNamespace: mobile-loadtest
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
  # 指定 kubeconfig
  kubeConfig:
    secretRef:
      name: stg-cn-northwest-kubeconfig
